jwt:
  secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629

auth:
  default_login: admin
  default_password: admin
  refresh_token_life_seconds: 60
  access_token_life_seconds: 1

spring:
  main.banner-mode: off
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      topics:
        topic-one-json: topic-one
        topic-two-json: topic-two
      auto-offset-reset: latest
    consumers:
      consumer-one:
        group-id: puppet
      consumer-two:
        group-id: puppetJson
    template:
      default-topic: default-puppet

my-setting-kafka:
  my-async:
    thread-pool:
      core-pool-size: 5
  my-customer:
    default-prop:
      concurrency: 3
    dynamic-prop:
      concurrency: 2
      interval: 1500
      max-attempts: 2

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    root: error
    my-async: info
    com.aston.frontendpracticeservice: info